services:
  postgres:
    container_name: ems-postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: Events-Management-System
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ems-network

  keycloak:
    container_name: ems-keycloak
    build:
      context: Keycloak/.
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - '8080:8080'
    volumes:
      - ./Keycloak/realm.json:/opt/keycloak/data/import/realm.json
    networks:
      - ems-network
    command:
      - start-dev
      - --import-realm
      - --features=scripts,admin-fine-grained-authz

  backend:
    container_name: ems-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    environment:
      ISSUER_URI: 'http://keycloak:8080/realms/EMS-realm'
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - ems-network
    env_file:
      - .env

  frontend:
    build: ./front-end
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_KEYCLOAK_BASE_URL=http://localhost:8080
      - REACT_APP_KEYCLOAK_REALM=EMS-realm
      - REACT_APP_KEYCLOAK_CLIENT_ID=ems-frontend
      - REACT_APP_API_BASE=http://localhost:8180
    depends_on:
      - keycloak
      - backend
    networks:
      - ems-network
volumes:
  postgres_data:
    name: ems-postgres-data
networks:
  ems-network:
    driver: bridge
