services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=Events-Management-System
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev
    ports:
      - '8180:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:8180
      KC_HOSTNAME_ADMIN_URL: http://localhost:8180