services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=Events-Management-System
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    ports:
      - '5432:5432'
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_URL=http://localhost:8180
      - KC_HOSTNAME_ADMIN_URL=http://localhost:8180
      - KC_FEATURES=scripts
    volumes:
      - C:/IntelliJ IDEA 2024.2.4/Keycloak-role-spi/target/Keycloak-role-spi-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/Keycloak-role-spi-0.0.1-SNAPSHOT.jar