spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ems_dev
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop


keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8081}
  realm: ${KEYCLOAK_REALM:EMS-realm}
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}     # if you insist on using admin-cli for ROPC
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}      # admin-cli has no secret by default
    username: ${KEYCLOAK_ADMIN_USERNAME:admin1}          # <— your realm admin user
    password: ${KEYCLOAK_ADMIN_PASSWORD:adminpass}  
  create:
    email-verified: false
    password-temporary: false

logging:
  level:
    com.example.cdr.eventsmanagementsystem.Aspect.LoggingAspect: INFO
    org:
      springframework:
        security:
          oauth2: trace
        web: debug
    com: debug

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never