spring:
  application:
    name: Events-Management-System
  datasource:
    url: jdbc:postgresql://postgres:5432/Events-Management-System
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: ${ISSUER_URI}
        jwk-set-uri: ${spring.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  stripe:
    api-key: ${SECRET_KEY}
logging:
  level:
    com.example.cdr.eventsmanagementsystem.Aspect.LoggingAspect: INFO
    org:
      springframework:
        security:
          oauth2: trace
        web: debug
    com: debug
server:
  port: 8180
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
app:
  payment:
    return-url: http://localhost:8180/v1/payments/confirm
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
  booking:
    free-cancel-days-before-start: 1
    penalty-percent: 0.20