spring:
  application:
    name: Events-Management-System
  datasource:
    url: jdbc:postgresql://postgres:5432/Events-Management-System
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: mahmoud.smtp.test@gmail.com
    password: qlos ofpo hkku twon
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/EMS-realm
  stripe:
    api-key: ${STRIPE_SECRET_KEY:sk_test_51RtDgxBHXOhVkYjpZM4hk3PuCYxLOaCX2e4zzTO9qJTq56mJMfJ3NBMSCXlxP0VZ0rtAFEuPqOzQMLUZ8CHAKmS200DzUHCMAM}
