spring:
  application:
    name: Events-Management-System (prod)

  datasource:
    url: jdbc:postgresql://postgres:5432/ems_prod

  jpa:
    hibernate:
      ddl-auto: update
payment:
  service:
    url: ${PAYMENT_SERVICE_URL:http://localhost:8082}
    enabled: true
