spring:
  application:
    name: Events-Management-System
  datasource:
    url: jdbc:postgresql://postgres:5432/Events-Management-System
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  stripe:
    api-key: ${SECRET_KEY}
    webhook:
      secret: ${STRIPE_WEBHOOK_SECRET}
      skip-verify: ${STRIPE_WEBHOOK_SKIP_VERIFY:false}
logging:
  level:
    com.example.cdr.eventsmanagementsystem.Aspect.LoggingAspect: INFO
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
app:
  payment:
    return-url: http://localhost:8180/v1/bookings/confirm
    success-url: http://localhost:8180/v1/bookings/confirm
    cancel-url: http://localhost:8180
  booking:
    free-cancel-days-before-start: 1
    penalty-percent: 0.20