apiVersion: v1
kind: ConfigMap
metadata:
  name: ems-postgres-config
data:
  postgresql.conf: |
    max_connections = 100
    shared_buffers = 256MB
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: ems-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ems-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ems-postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: ems-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: Events-Management-System
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: postgres-username
                  name: ems-secrets
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgres-password
                  name: ems-secrets
          volumeMounts:
            - mountPath: /etc/postgresql
              name: config-volume
            - mountPath: /var/lib/postgresql/data
              name: data
      volumes:
        - name: config-volume
          configMap:
            name: ems-postgres-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi