apiVersion: v1
kind: Secret
metadata:
  name: ems-secrets
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXM=
  keycloak-username: YWRtaW4=
  keycloak-password: YWRtaW4=
  secret-key: c2tfdGVzdF81MVJ1RjJTRk5DM1JRd1JzcnlxS25XOWFWa1dHc1ZrbGdDWmp4RXdPZDNNTDNCNDVUeURQT1ljbUtYeVk5bWlxNHZXbW9aTGZDeUVqOEVFZkNzTXdrZGlKTjAwT2NDV0RodGo=
  issuer-uri: aHR0cDovL2tleWNsb2FrOjgwODAvcmVhbG1zL0VNUy1yZWFsbQ==
  client-secret: WXd4bWgyR2FZRk5jRHJjQ3dIenlsQjNnRkRzSE5hVE4=