/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ittovative.ems.payment.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentProvider implements org.apache.avro.generic.GenericEnumSymbol<PaymentProvider> {
  STRIPE, AYDEN, PAYPAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentProvider\",\"namespace\":\"com.ittovative.ems.payment.avro\",\"symbols\":[\"STRIPE\",\"AYDEN\",\"PAYPAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
