/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ittovative.ems.payment.avro;
@org.apache.avro.specific.AvroGenerated
public enum PaymentStatus implements org.apache.avro.generic.GenericEnumSymbol<PaymentStatus> {
  SUCCEEDED, FAILED, REFUNDED, CANCELLED, PENDING, EXPIRED, PARTIALLY_REFUNDED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"namespace\":\"com.ittovative.ems.payment.avro\",\"symbols\":[\"SUCCEEDED\",\"FAILED\",\"REFUNDED\",\"CANCELLED\",\"PENDING\",\"EXPIRED\",\"PARTIALLY_REFUNDED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
