/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ittovative.ems.payment.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Generic payment status event for multiple payment providers */
@org.apache.avro.specific.AvroGenerated
public class PaymentStatusEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1984030591573181177L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentStatusEvent\",\"namespace\":\"com.ittovative.ems.payment.avro\",\"doc\":\"Generic payment status event for multiple payment providers\",\"fields\":[{\"name\":\"systemId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Identifier for the source system\"},{\"name\":\"bookingId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier for the booking in EMS\"},{\"name\":\"paymentStatus\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"symbols\":[\"SUCCEEDED\",\"FAILED\",\"REFUNDED\",\"CANCELLED\",\"PENDING\",\"EXPIRED\",\"PARTIALLY_REFUNDED\"]},\"doc\":\"Current status of the payment\"},{\"name\":\"paymentProvider\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentProvider\",\"symbols\":[\"STRIPE\",\"AYDEN\",\"PAYPAL\"]},\"doc\":\"Payment provider identifier\"},{\"name\":\"referenceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Transaction ID from the payment provider\"},{\"name\":\"amount\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Payment amount as string\"},{\"name\":\"currency\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Currency code (e.g., USD, EUR)\"},{\"name\":\"timestamp\",\"type\":\"long\",\"doc\":\"Event timestamp in milliseconds since epoch\"},{\"name\":\"failureReason\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Generic failure reason if payment failed\",\"default\":null},{\"name\":\"metadata\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}],\"doc\":\"Additional metadata including bookingType and other custom fields\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentStatusEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentStatusEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentStatusEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentStatusEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentStatusEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentStatusEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentStatusEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentStatusEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentStatusEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Identifier for the source system */
  private java.lang.String systemId;
  /** Unique identifier for the booking in EMS */
  private java.lang.String bookingId;
  /** Current status of the payment */
  private com.ittovative.ems.payment.avro.PaymentStatus paymentStatus;
  /** Payment provider identifier */
  private com.ittovative.ems.payment.avro.PaymentProvider paymentProvider;
  /** Transaction ID from the payment provider */
  private java.lang.String referenceId;
  /** Payment amount as string */
  private java.lang.String amount;
  /** Currency code (e.g., USD, EUR) */
  private java.lang.String currency;
  /** Event timestamp in milliseconds since epoch */
  private long timestamp;
  /** Generic failure reason if payment failed */
  private java.lang.String failureReason;
  /** Additional metadata including bookingType and other custom fields */
  private java.util.Map<java.lang.String,java.lang.String> metadata;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentStatusEvent() {}

  /**
   * All-args constructor.
   * @param systemId Identifier for the source system
   * @param bookingId Unique identifier for the booking in EMS
   * @param paymentStatus Current status of the payment
   * @param paymentProvider Payment provider identifier
   * @param referenceId Transaction ID from the payment provider
   * @param amount Payment amount as string
   * @param currency Currency code (e.g., USD, EUR)
   * @param timestamp Event timestamp in milliseconds since epoch
   * @param failureReason Generic failure reason if payment failed
   * @param metadata Additional metadata including bookingType and other custom fields
   */
  public PaymentStatusEvent(java.lang.String systemId, java.lang.String bookingId, com.ittovative.ems.payment.avro.PaymentStatus paymentStatus, com.ittovative.ems.payment.avro.PaymentProvider paymentProvider, java.lang.String referenceId, java.lang.String amount, java.lang.String currency, java.lang.Long timestamp, java.lang.String failureReason, java.util.Map<java.lang.String,java.lang.String> metadata) {
    this.systemId = systemId;
    this.bookingId = bookingId;
    this.paymentStatus = paymentStatus;
    this.paymentProvider = paymentProvider;
    this.referenceId = referenceId;
    this.amount = amount;
    this.currency = currency;
    this.timestamp = timestamp;
    this.failureReason = failureReason;
    this.metadata = metadata;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return systemId;
    case 1: return bookingId;
    case 2: return paymentStatus;
    case 3: return paymentProvider;
    case 4: return referenceId;
    case 5: return amount;
    case 6: return currency;
    case 7: return timestamp;
    case 8: return failureReason;
    case 9: return metadata;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: systemId = value$ != null ? value$.toString() : null; break;
    case 1: bookingId = value$ != null ? value$.toString() : null; break;
    case 2: paymentStatus = (com.ittovative.ems.payment.avro.PaymentStatus)value$; break;
    case 3: paymentProvider = (com.ittovative.ems.payment.avro.PaymentProvider)value$; break;
    case 4: referenceId = value$ != null ? value$.toString() : null; break;
    case 5: amount = value$ != null ? value$.toString() : null; break;
    case 6: currency = value$ != null ? value$.toString() : null; break;
    case 7: timestamp = (java.lang.Long)value$; break;
    case 8: failureReason = value$ != null ? value$.toString() : null; break;
    case 9: metadata = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'systemId' field.
   * @return Identifier for the source system
   */
  public java.lang.String getSystemId() {
    return systemId;
  }


  /**
   * Sets the value of the 'systemId' field.
   * Identifier for the source system
   * @param value the value to set.
   */
  public void setSystemId(java.lang.String value) {
    this.systemId = value;
  }

  /**
   * Gets the value of the 'bookingId' field.
   * @return Unique identifier for the booking in EMS
   */
  public java.lang.String getBookingId() {
    return bookingId;
  }


  /**
   * Sets the value of the 'bookingId' field.
   * Unique identifier for the booking in EMS
   * @param value the value to set.
   */
  public void setBookingId(java.lang.String value) {
    this.bookingId = value;
  }

  /**
   * Gets the value of the 'paymentStatus' field.
   * @return Current status of the payment
   */
  public com.ittovative.ems.payment.avro.PaymentStatus getPaymentStatus() {
    return paymentStatus;
  }


  /**
   * Sets the value of the 'paymentStatus' field.
   * Current status of the payment
   * @param value the value to set.
   */
  public void setPaymentStatus(com.ittovative.ems.payment.avro.PaymentStatus value) {
    this.paymentStatus = value;
  }

  /**
   * Gets the value of the 'paymentProvider' field.
   * @return Payment provider identifier
   */
  public com.ittovative.ems.payment.avro.PaymentProvider getPaymentProvider() {
    return paymentProvider;
  }


  /**
   * Sets the value of the 'paymentProvider' field.
   * Payment provider identifier
   * @param value the value to set.
   */
  public void setPaymentProvider(com.ittovative.ems.payment.avro.PaymentProvider value) {
    this.paymentProvider = value;
  }

  /**
   * Gets the value of the 'referenceId' field.
   * @return Transaction ID from the payment provider
   */
  public java.lang.String getReferenceId() {
    return referenceId;
  }


  /**
   * Sets the value of the 'referenceId' field.
   * Transaction ID from the payment provider
   * @param value the value to set.
   */
  public void setReferenceId(java.lang.String value) {
    this.referenceId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return Payment amount as string
   */
  public java.lang.String getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * Payment amount as string
   * @param value the value to set.
   */
  public void setAmount(java.lang.String value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return Currency code (e.g., USD, EUR)
   */
  public java.lang.String getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * Currency code (e.g., USD, EUR)
   * @param value the value to set.
   */
  public void setCurrency(java.lang.String value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return Event timestamp in milliseconds since epoch
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * Event timestamp in milliseconds since epoch
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'failureReason' field.
   * @return Generic failure reason if payment failed
   */
  public java.lang.String getFailureReason() {
    return failureReason;
  }


  /**
   * Sets the value of the 'failureReason' field.
   * Generic failure reason if payment failed
   * @param value the value to set.
   */
  public void setFailureReason(java.lang.String value) {
    this.failureReason = value;
  }

  /**
   * Gets the value of the 'metadata' field.
   * @return Additional metadata including bookingType and other custom fields
   */
  public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
    return metadata;
  }


  /**
   * Sets the value of the 'metadata' field.
   * Additional metadata including bookingType and other custom fields
   * @param value the value to set.
   */
  public void setMetadata(java.util.Map<java.lang.String,java.lang.String> value) {
    this.metadata = value;
  }

  /**
   * Creates a new PaymentStatusEvent RecordBuilder.
   * @return A new PaymentStatusEvent RecordBuilder
   */
  public static com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder newBuilder() {
    return new com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder();
  }

  /**
   * Creates a new PaymentStatusEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentStatusEvent RecordBuilder
   */
  public static com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder newBuilder(com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder other) {
    if (other == null) {
      return new com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder();
    } else {
      return new com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder(other);
    }
  }

  /**
   * Creates a new PaymentStatusEvent RecordBuilder by copying an existing PaymentStatusEvent instance.
   * @param other The existing instance to copy.
   * @return A new PaymentStatusEvent RecordBuilder
   */
  public static com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder newBuilder(com.ittovative.ems.payment.avro.PaymentStatusEvent other) {
    if (other == null) {
      return new com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder();
    } else {
      return new com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentStatusEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentStatusEvent>
    implements org.apache.avro.data.RecordBuilder<PaymentStatusEvent> {

    /** Identifier for the source system */
    private java.lang.String systemId;
    /** Unique identifier for the booking in EMS */
    private java.lang.String bookingId;
    /** Current status of the payment */
    private com.ittovative.ems.payment.avro.PaymentStatus paymentStatus;
    /** Payment provider identifier */
    private com.ittovative.ems.payment.avro.PaymentProvider paymentProvider;
    /** Transaction ID from the payment provider */
    private java.lang.String referenceId;
    /** Payment amount as string */
    private java.lang.String amount;
    /** Currency code (e.g., USD, EUR) */
    private java.lang.String currency;
    /** Event timestamp in milliseconds since epoch */
    private long timestamp;
    /** Generic failure reason if payment failed */
    private java.lang.String failureReason;
    /** Additional metadata including bookingType and other custom fields */
    private java.util.Map<java.lang.String,java.lang.String> metadata;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.systemId)) {
        this.systemId = data().deepCopy(fields()[0].schema(), other.systemId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bookingId)) {
        this.bookingId = data().deepCopy(fields()[1].schema(), other.bookingId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.paymentStatus)) {
        this.paymentStatus = data().deepCopy(fields()[2].schema(), other.paymentStatus);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.paymentProvider)) {
        this.paymentProvider = data().deepCopy(fields()[3].schema(), other.paymentProvider);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.referenceId)) {
        this.referenceId = data().deepCopy(fields()[4].schema(), other.referenceId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.currency)) {
        this.currency = data().deepCopy(fields()[6].schema(), other.currency);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.failureReason)) {
        this.failureReason = data().deepCopy(fields()[8].schema(), other.failureReason);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.metadata)) {
        this.metadata = data().deepCopy(fields()[9].schema(), other.metadata);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentStatusEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ittovative.ems.payment.avro.PaymentStatusEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.systemId)) {
        this.systemId = data().deepCopy(fields()[0].schema(), other.systemId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bookingId)) {
        this.bookingId = data().deepCopy(fields()[1].schema(), other.bookingId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.paymentStatus)) {
        this.paymentStatus = data().deepCopy(fields()[2].schema(), other.paymentStatus);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.paymentProvider)) {
        this.paymentProvider = data().deepCopy(fields()[3].schema(), other.paymentProvider);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.referenceId)) {
        this.referenceId = data().deepCopy(fields()[4].schema(), other.referenceId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.currency)) {
        this.currency = data().deepCopy(fields()[6].schema(), other.currency);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[7].schema(), other.timestamp);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.failureReason)) {
        this.failureReason = data().deepCopy(fields()[8].schema(), other.failureReason);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.metadata)) {
        this.metadata = data().deepCopy(fields()[9].schema(), other.metadata);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'systemId' field.
      * Identifier for the source system
      * @return The value.
      */
    public java.lang.String getSystemId() {
      return systemId;
    }


    /**
      * Sets the value of the 'systemId' field.
      * Identifier for the source system
      * @param value The value of 'systemId'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setSystemId(java.lang.String value) {
      validate(fields()[0], value);
      this.systemId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'systemId' field has been set.
      * Identifier for the source system
      * @return True if the 'systemId' field has been set, false otherwise.
      */
    public boolean hasSystemId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'systemId' field.
      * Identifier for the source system
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearSystemId() {
      systemId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookingId' field.
      * Unique identifier for the booking in EMS
      * @return The value.
      */
    public java.lang.String getBookingId() {
      return bookingId;
    }


    /**
      * Sets the value of the 'bookingId' field.
      * Unique identifier for the booking in EMS
      * @param value The value of 'bookingId'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setBookingId(java.lang.String value) {
      validate(fields()[1], value);
      this.bookingId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bookingId' field has been set.
      * Unique identifier for the booking in EMS
      * @return True if the 'bookingId' field has been set, false otherwise.
      */
    public boolean hasBookingId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bookingId' field.
      * Unique identifier for the booking in EMS
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearBookingId() {
      bookingId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentStatus' field.
      * Current status of the payment
      * @return The value.
      */
    public com.ittovative.ems.payment.avro.PaymentStatus getPaymentStatus() {
      return paymentStatus;
    }


    /**
      * Sets the value of the 'paymentStatus' field.
      * Current status of the payment
      * @param value The value of 'paymentStatus'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setPaymentStatus(com.ittovative.ems.payment.avro.PaymentStatus value) {
      validate(fields()[2], value);
      this.paymentStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentStatus' field has been set.
      * Current status of the payment
      * @return True if the 'paymentStatus' field has been set, false otherwise.
      */
    public boolean hasPaymentStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'paymentStatus' field.
      * Current status of the payment
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearPaymentStatus() {
      paymentStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentProvider' field.
      * Payment provider identifier
      * @return The value.
      */
    public com.ittovative.ems.payment.avro.PaymentProvider getPaymentProvider() {
      return paymentProvider;
    }


    /**
      * Sets the value of the 'paymentProvider' field.
      * Payment provider identifier
      * @param value The value of 'paymentProvider'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setPaymentProvider(com.ittovative.ems.payment.avro.PaymentProvider value) {
      validate(fields()[3], value);
      this.paymentProvider = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentProvider' field has been set.
      * Payment provider identifier
      * @return True if the 'paymentProvider' field has been set, false otherwise.
      */
    public boolean hasPaymentProvider() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'paymentProvider' field.
      * Payment provider identifier
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearPaymentProvider() {
      paymentProvider = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'referenceId' field.
      * Transaction ID from the payment provider
      * @return The value.
      */
    public java.lang.String getReferenceId() {
      return referenceId;
    }


    /**
      * Sets the value of the 'referenceId' field.
      * Transaction ID from the payment provider
      * @param value The value of 'referenceId'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setReferenceId(java.lang.String value) {
      validate(fields()[4], value);
      this.referenceId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'referenceId' field has been set.
      * Transaction ID from the payment provider
      * @return True if the 'referenceId' field has been set, false otherwise.
      */
    public boolean hasReferenceId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'referenceId' field.
      * Transaction ID from the payment provider
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearReferenceId() {
      referenceId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * Payment amount as string
      * @return The value.
      */
    public java.lang.String getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * Payment amount as string
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setAmount(java.lang.String value) {
      validate(fields()[5], value);
      this.amount = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * Payment amount as string
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'amount' field.
      * Payment amount as string
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * Currency code (e.g., USD, EUR)
      * @return The value.
      */
    public java.lang.String getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * Currency code (e.g., USD, EUR)
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setCurrency(java.lang.String value) {
      validate(fields()[6], value);
      this.currency = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * Currency code (e.g., USD, EUR)
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'currency' field.
      * Currency code (e.g., USD, EUR)
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * Event timestamp in milliseconds since epoch
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * Event timestamp in milliseconds since epoch
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setTimestamp(long value) {
      validate(fields()[7], value);
      this.timestamp = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * Event timestamp in milliseconds since epoch
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * Event timestamp in milliseconds since epoch
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearTimestamp() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'failureReason' field.
      * Generic failure reason if payment failed
      * @return The value.
      */
    public java.lang.String getFailureReason() {
      return failureReason;
    }


    /**
      * Sets the value of the 'failureReason' field.
      * Generic failure reason if payment failed
      * @param value The value of 'failureReason'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setFailureReason(java.lang.String value) {
      validate(fields()[8], value);
      this.failureReason = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'failureReason' field has been set.
      * Generic failure reason if payment failed
      * @return True if the 'failureReason' field has been set, false otherwise.
      */
    public boolean hasFailureReason() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'failureReason' field.
      * Generic failure reason if payment failed
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearFailureReason() {
      failureReason = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'metadata' field.
      * Additional metadata including bookingType and other custom fields
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getMetadata() {
      return metadata;
    }


    /**
      * Sets the value of the 'metadata' field.
      * Additional metadata including bookingType and other custom fields
      * @param value The value of 'metadata'.
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder setMetadata(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[9], value);
      this.metadata = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'metadata' field has been set.
      * Additional metadata including bookingType and other custom fields
      * @return True if the 'metadata' field has been set, false otherwise.
      */
    public boolean hasMetadata() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'metadata' field.
      * Additional metadata including bookingType and other custom fields
      * @return This builder.
      */
    public com.ittovative.ems.payment.avro.PaymentStatusEvent.Builder clearMetadata() {
      metadata = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentStatusEvent build() {
      try {
        PaymentStatusEvent record = new PaymentStatusEvent();
        record.systemId = fieldSetFlags()[0] ? this.systemId : (java.lang.String) defaultValue(fields()[0]);
        record.bookingId = fieldSetFlags()[1] ? this.bookingId : (java.lang.String) defaultValue(fields()[1]);
        record.paymentStatus = fieldSetFlags()[2] ? this.paymentStatus : (com.ittovative.ems.payment.avro.PaymentStatus) defaultValue(fields()[2]);
        record.paymentProvider = fieldSetFlags()[3] ? this.paymentProvider : (com.ittovative.ems.payment.avro.PaymentProvider) defaultValue(fields()[3]);
        record.referenceId = fieldSetFlags()[4] ? this.referenceId : (java.lang.String) defaultValue(fields()[4]);
        record.amount = fieldSetFlags()[5] ? this.amount : (java.lang.String) defaultValue(fields()[5]);
        record.currency = fieldSetFlags()[6] ? this.currency : (java.lang.String) defaultValue(fields()[6]);
        record.timestamp = fieldSetFlags()[7] ? this.timestamp : (java.lang.Long) defaultValue(fields()[7]);
        record.failureReason = fieldSetFlags()[8] ? this.failureReason : (java.lang.String) defaultValue(fields()[8]);
        record.metadata = fieldSetFlags()[9] ? this.metadata : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[9]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentStatusEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentStatusEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentStatusEvent>
    READER$ = (org.apache.avro.io.DatumReader<PaymentStatusEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.systemId);

    out.writeString(this.bookingId);

    out.writeEnum(this.paymentStatus.ordinal());

    out.writeEnum(this.paymentProvider.ordinal());

    out.writeString(this.referenceId);

    out.writeString(this.amount);

    out.writeString(this.currency);

    out.writeLong(this.timestamp);

    if (this.failureReason == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.failureReason);
    }

    if (this.metadata == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.metadata.size();
      out.writeMapStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> e0: this.metadata.entrySet()) {
        actualSize0++;
        out.startItem();
        out.writeString(e0.getKey());
        java.lang.String v0 = e0.getValue();
        out.writeString(v0);
      }
      out.writeMapEnd();
      if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.systemId = in.readString();

      this.bookingId = in.readString();

      this.paymentStatus = com.ittovative.ems.payment.avro.PaymentStatus.values()[in.readEnum()];

      this.paymentProvider = com.ittovative.ems.payment.avro.PaymentProvider.values()[in.readEnum()];

      this.referenceId = in.readString();

      this.amount = in.readString();

      this.currency = in.readString();

      this.timestamp = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.failureReason = null;
      } else {
        this.failureReason = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.metadata = null;
      } else {
        long size0 = in.readMapStart();
        java.util.Map<java.lang.String,java.lang.String> m0 = this.metadata; // Need fresh name due to limitation of macro system
        if (m0 == null) {
          m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)(size0 * 4)/3 + 1);
          this.metadata = m0;
        } else m0.clear();
        for ( ; 0 < size0; size0 = in.mapNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.String k0 = null;
            k0 = in.readString();
            java.lang.String v0 = null;
            v0 = in.readString();
            m0.put(k0, v0);
          }
        }
      }

    } else {
      for (int i = 0; i < 10; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.systemId = in.readString();
          break;

        case 1:
          this.bookingId = in.readString();
          break;

        case 2:
          this.paymentStatus = com.ittovative.ems.payment.avro.PaymentStatus.values()[in.readEnum()];
          break;

        case 3:
          this.paymentProvider = com.ittovative.ems.payment.avro.PaymentProvider.values()[in.readEnum()];
          break;

        case 4:
          this.referenceId = in.readString();
          break;

        case 5:
          this.amount = in.readString();
          break;

        case 6:
          this.currency = in.readString();
          break;

        case 7:
          this.timestamp = in.readLong();
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.failureReason = null;
          } else {
            this.failureReason = in.readString();
          }
          break;

        case 9:
          if (in.readIndex() != 1) {
            in.readNull();
            this.metadata = null;
          } else {
            long size0 = in.readMapStart();
            java.util.Map<java.lang.String,java.lang.String> m0 = this.metadata; // Need fresh name due to limitation of macro system
            if (m0 == null) {
              m0 = new java.util.HashMap<java.lang.String,java.lang.String>((int)(size0 * 4)/3 + 1);
              this.metadata = m0;
            } else m0.clear();
            for ( ; 0 < size0; size0 = in.mapNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.String k0 = null;
                k0 = in.readString();
                java.lang.String v0 = null;
                v0 = in.readString();
                m0.put(k0, v0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










