package com.example.cdr.eventsmanagementsystem.Model.Event;

public enum EventType {
    WEDDING,
    ENGAGEMENT_PARTY,
    BIRTHDAY_PARTY,
    FAMILY_REUNION,
    PRIVATE_DINNER,
    RETREAT,
    BACHELORETTE_PARTY,
    BABY_SHOWER,

    CONFERENCE,
    WORKSHOP,
    SEMINAR,
    CORPORATE_DINNER,
    NETWORKING_EVENT,
    PRODUCT_LAUNCH,
    AWARD_CEREMONY,
    FASHION_SHOW,
    BUSINESS_EXPO,
    FUNDRAISER,
}