INSERT INTO event_type (name, description) VALUES
  ('WEDDING', 'Wedding ceremonies and receptions'),
  ('ENGAGEMENT_PARTY', 'Engagement celebration parties'),
  ('BIRTHDAY_PARTY', 'Birthday celebrations'),
  ('FAMILY_REUNION', 'Family gatherings and reunions'),
  ('PRIVATE_DINNER', 'Private dining events'),
  ('RETREAT', 'Corporate or wellness retreats'),
  ('BACHELORETTE_PARTY', 'Bachelorette celebrations'),
  ('BABY_SHOWER', 'Baby shower events'),
  ('CONFERENCE', 'Business conferences and meetings'),
  ('WORKSHOP', 'Training and educational workshops'),
  ('SEMINAR', 'Academic and professional seminars'),
  ('CORPORATE_DINNER', 'Corporate dining events'),
  ('NETWORKING_EVENT', 'Professional networking gatherings'),
  ('PRODUCT_LAUNCH', 'Product launch events'),
  ('AWARD_CEREMONY', 'Award ceremonies and galas'),
  ('FASHION_SHOW', 'Fashion shows and presentations'),
  ('BUSINESS_EXPO', 'Business exhibitions and expos'),
  ('FUNDRAISER', 'Fundraising events and galas');
