INSERT INTO venue_event_eligibility (venue_type_id, event_type_id)
SELECT vt.id, et.id
FROM venue_type vt CROSS JOIN event_type et
WHERE
    (vt.name IN ('VILLA', 'CHALET', 'FARMHOUSE') AND et.name IN ('WEDDING','ENGAGEMENT_PARTY','BIRTHDAY_PARTY','FAMILY_REUNION','PRIVATE_DINNER','RETREAT','BACHELORETTE_PARTY','BABY_SHOWER'))
   OR
    (vt.name IN ('HOTEL','RESTAURANT','CONFERENCE_CENTER','CLUB') AND et.name IN ('CONFERENCE','WORKSHOP','SEMINAR','CORPORATE_DINNER','NETWORKING_EVENT','PRODUCT_LAUNCH','AWARD_CEREMONY','FASHION_SHOW','BUSINESS_EXPO','FUNDRAISER'))
   OR
    (vt.name IN ('SCHOOL_HALL','UNIVERSITY_AUDITORIUM') AND et.name IN ('WORKSHOP','SEMINAR','CONFERENCE'))
   OR
    (vt.name IN ('PARK','GARDEN','BEACH') AND et.name IN ('WEDDING','FUNDRAISER','NETWORKING_EVENT'))
   OR
    (vt.name IN ('THEATER','ART_GALLERY','SPORTS_ARENA') AND et.name IN ('CONFERENCE','WORKSHOP','AWARD_CEREMONY','FASHION_SHOW','PRODUCT_LAUNCH','BUSINESS_EXPO'));